name: Build Binary
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lib-binary
          path: lib

